/**
 * CENTRALIZED CATEGORY -> SUBCATEGORY -> FIXED XP MAPPING
 * 
 * SOLE SOURCE OF TRUTH FOR ALL CATEGORY / SUBCATEGORY XP IN ANTISOCIAL.
 * - 100 Categories
 * - 2,000 Activities (20 per category)
 * - 152,220 Total Possible XP
 * - Minimum XP: 10
 * - Maximum XP: 500
 * - Average XP: 76.11
 * 
 * Top-level categories themselves award NO additional XP.
 * Only the selected subcategory/activity awards its fixed XP.
 */

const CATEGORY_XP_MAP = {
  "Achievements": {
    "Academic Wins": 150,
    "Career Wins": 250,
    "Sports Wins": 150,
    "Fitness Milestones": 100,
    "Project Completion": 100,
    "Competition Wins": 250,
    "Certifications": 150,
    "First-Time Achievements": 200,
    "Personal Records": 250,
    "Financial Milestones": 300,
    "Creative Achievements": 150,
    "Skill Milestones": 150,
    "Habit Streaks": 100,
    "Goal Completion": 150,
    "Overcoming Fear": 250,
    "Major Life Milestones": 400,
    "Team Achievements": 150,
    "Community Impact": 300,
    "Comeback Stories": 350,
    "Milestone Unlocked": 200
  },
  "Advice": {
    "Career Advice": 100,
    "Study Advice": 70,
    "Fitness Advice": 80,
    "Money Advice": 120,
    "Relationship Advice": 120,
    "Travel Advice": 70,
    "Food Advice": 50,
    "Productivity Advice": 80,
    "College Advice": 60,
    "Coding Advice": 100,
    "Business Advice": 150,
    "Communication Advice": 100,
    "Confidence Advice": 100,
    "Decision Making": 150,
    "Time Management": 100,
    "Health Habits": 100,
    "Social Skills": 120,
    "Problem Solving": 150,
    "Life Decisions": 200,
    "Beginner Guidance": 40
  },
  "Adventures": {
    "Skydiving": 500,
    "Scuba Diving": 400,
    "Paragliding": 400,
    "Bungee Jumping": 350,
    "Rock Climbing": 350,
    "Whitewater Rafting": 400,
    "Ziplining": 200,
    "Trekking": 200,
    "Mountain Climbing": 450,
    "Caving": 350,
    "Surfing": 350,
    "Kayaking": 300,
    "Snowboarding": 350,
    "Skiing": 350,
    "Safari": 250,
    "Jungle Trek": 300,
    "Desert Safari": 250,
    "Hot Air Balloon": 250,
    "Motorcycle Trip": 300,
    "Long-Distance Road Trip": 300
  },
  "Animals": {
    "Dogs": 20,
    "Cats": 20,
    "Birds": 30,
    "Fish": 20,
    "Horses": 80,
    "Rabbits": 30,
    "Hamsters": 20,
    "Guinea Pigs": 20,
    "Reptiles": 80,
    "Turtles": 40,
    "Snakes": 100,
    "Butterflies": 30,
    "Bees": 40,
    "Dolphins": 150,
    "Whales": 200,
    "Elephants": 200,
    "Tigers": 250,
    "Lions": 250,
    "Pandas": 150,
    "Wildlife": 250
  },
  "Anime": {
    "Action Anime": 40,
    "Adventure Anime": 40,
    "Comedy Anime": 30,
    "Romance Anime": 30,
    "Fantasy Anime": 40,
    "Isekai Anime": 40,
    "Sports Anime": 40,
    "School Anime": 30,
    "Slice of Life": 30,
    "Mecha Anime": 50,
    "Mystery Anime": 50,
    "Horror Anime": 50,
    "Psychological Anime": 80,
    "Shonen Anime": 40,
    "Shojo Anime": 40,
    "Seinen Anime": 50,
    "Josei Anime": 50,
    "Anime Movies": 50,
    "Anime Characters": 30,
    "Anime Recommendations": 20
  },
  "Architecture": {
    "Residential Architecture": 50,
    "Commercial Buildings": 70,
    "Skyscrapers": 100,
    "Brutalist Architecture": 100,
    "Gothic Architecture": 120,
    "Modern Architecture": 80,
    "Minimalist Architecture": 60,
    "Traditional Architecture": 80,
    "Japanese Architecture": 100,
    "Islamic Architecture": 100,
    "Indian Architecture": 100,
    "Roman Architecture": 120,
    "Greek Architecture": 120,
    "Sustainable Architecture": 150,
    "Interior Architecture": 100,
    "Landscape Architecture": 100,
    "Urban Design": 150,
    "Historic Buildings": 150,
    "Famous Structures": 100,
    "Architectural Details": 80
  },
  "Art": {
    "Oil Painting": 200,
    "Watercolor": 120,
    "Acrylic Painting": 120,
    "Sketching": 80,
    "Pencil Drawing": 80,
    "Charcoal Drawing": 100,
    "Digital Art": 120,
    "Portrait Art": 180,
    "Landscape Art": 120,
    "Abstract Art": 100,
    "Calligraphy": 100,
    "Typography Art": 80,
    "Sculpture": 250,
    "Clay Art": 150,
    "Origami": 80,
    "Paper Art": 80,
    "Collage": 60,
    "Street Art": 150,
    "Graffiti": 150,
    "Art Journaling": 70
  },
  "Astronomy": {
    "Moon": 30,
    "Sun": 30,
    "Planets": 40,
    "Stars": 40,
    "Constellations": 50,
    "Galaxies": 70,
    "Nebulae": 80,
    "Black Holes": 120,
    "Comets": 60,
    "Asteroids": 60,
    "Meteors": 50,
    "Eclipses": 70,
    "Aurora": 100,
    "Space Missions": 120,
    "Space Telescopes": 150,
    "Exoplanets": 150,
    "Milky Way": 100,
    "Cosmology": 200,
    "Astronauts": 100,
    "Stargazing": 80
  },
  "Automotive": {
    "Sedans": 30,
    "SUVs": 40,
    "Hatchbacks": 30,
    "Sports Cars": 100,
    "Supercars": 150,
    "Hypercars": 200,
    "Electric Cars": 80,
    "Hybrid Cars": 70,
    "Classic Cars": 100,
    "Muscle Cars": 100,
    "Luxury Cars": 80,
    "Pickup Trucks": 50,
    "Off-Road Vehicles": 120,
    "Rally Cars": 150,
    "Race Cars": 180,
    "Car Modifications": 120,
    "Car Detailing": 60,
    "Car Photography": 50,
    "Car Meets": 40,
    "Driving": 100
  },
  "Badminton": {
    "Singles": 150,
    "Doubles": 70,
    "Mixed Doubles": 80,
    "Professional Badminton": 300,
    "Club Badminton": 60,
    "School Badminton": 40,
    "Badminton Training": 100,
    "Smash": 120,
    "Drop Shot": 100,
    "Clear Shot": 90,
    "Net Play": 100,
    "Footwork": 120,
    "Badminton Fitness": 100,
    "Badminton Rackets": 40,
    "Badminton Shoes": 30,
    "Badminton Courts": 20,
    "Badminton Tournaments": 120,
    "Match Highlights": 30,
    "Badminton Players": 30,
    "Badminton News": 20
  },
  "Basketball": {
    "NBA": 300,
    "WNBA": 30,
    "College Basketball": 40,
    "Street Basketball": 50,
    "3x3 Basketball": 60,
    "International Basketball": 40,
    "Basketball Training": 100,
    "Dribbling": 100,
    "Shooting": 120,
    "Dunking": 180,
    "Defense": 120,
    "Rebounding": 100,
    "Basketball Fitness": 100,
    "Basketball Gear": 30,
    "Basketball Courts": 20,
    "Basketball Tournaments": 120,
    "Basketball Highlights": 30,
    "Basketball Records": 80,
    "Basketball Players": 30,
    "Basketball News": 20
  },
  "Books": {
    "Fiction": 100,
    "Non-Fiction": 40,
    "Mystery": 40,
    "Thriller": 80,
    "Romance": 30,
    "Fantasy": 40,
    "Science Fiction": 50,
    "Biography": 70,
    "Autobiography": 350,
    "Self-Help": 60,
    "Psychology": 80,
    "Business Books": 70,
    "Finance Books": 80,
    "History Books": 80,
    "Science Books": 100,
    "Philosophy": 120,
    "Poetry": 70,
    "Comics": 30,
    "Manga": 30,
    "Graphic Novels": 40
  },
  "Business": {
    "Business Ideas": 100,
    "Small Business": 120,
    "E-Commerce": 100,
    "Retail": 70,
    "Marketing": 100,
    "Sales": 120,
    "Operations": 130,
    "Management": 150,
    "Customer Service": 70,
    "Business Strategy": 180,
    "Branding": 100,
    "Business Analytics": 150,
    "Franchising": 150,
    "Family Business": 100,
    "B2B": 100,
    "B2C": 80,
    "Local Business": 70,
    "Online Business": 100,
    "Business Case Studies": 120,
    "Business News": 30
  },
  "Career": {
    "Programming": 120,
    "Software Development": 180,
    "UI/UX Design": 120,
    "Data Science": 180,
    "Cybersecurity": 200,
    "Digital Marketing": 100,
    "Sales": 120,
    "Finance": 150,
    "Accounting": 130,
    "Human Resources": 100,
    "Project Management": 180,
    "Product Management": 180,
    "Business Analysis": 160,
    "Consulting": 180,
    "Content Creation": 100,
    "Graphic Design": 100,
    "Video Editing": 100,
    "Teaching": 120,
    "Healthcare": 150,
    "Freelancing": 120
  },
  "Coding": {
    "Programming": 120,
    "Software Development": 180,
    "UI/UX Design": 120,
    "Data Science": 180,
    "Cybersecurity": 200,
    "Digital Marketing": 100,
    "Sales": 80,
    "Finance": 120,
    "Accounting": 100,
    "Human Resources": 80,
    "Project Management": 150,
    "Product Management": 150,
    "Business Analysis": 140,
    "Consulting": 150,
    "Content Creation": 80,
    "Graphic Design": 90,
    "Video Editing": 90,
    "Teaching": 100,
    "Healthcare": 120,
    "Freelancing": 100
  },
  "College Life": {
    "College Classes": 40,
    "Campus Life": 30,
    "College Friends": 50,
    "College Clubs": 60,
    "College Festivals": 60,
    "College Events": 60,
    "College Projects": 120,
    "College Assignments": 70,
    "College Exams": 100,
    "Hostel Life": 100,
    "College Sports": 60,
    "College Canteen": 20,
    "College Trips": 100,
    "College Memories": 60,
    "Freshers": 50,
    "Graduation": 200,
    "Student Communities": 60,
    "Internships": 150,
    "College Competitions": 120,
    "Student Life": 50
  },
  "Comedy": {
    "Stand-Up Comedy": 80,
    "Sketch Comedy": 60,
    "Situational Comedy": 50,
    "Dark Comedy": 60,
    "Observational Comedy": 70,
    "Satire": 80,
    "Parody": 60,
    "Pranks": 50,
    "Funny Stories": 40,
    "Funny Videos": 30,
    "Funny Photos": 20,
    "One-Liners": 20,
    "Dad Jokes": 10,
    "Roasts": 40,
    "Impressions": 80,
    "Comedy Shows": 40,
    "Comedy Movies": 30,
    "Comedy Reactions": 20,
    "Funny Fails": 20,
    "Everyday Humor": 20
  },
  "Community": {
    "Local Communities": 60,
    "Student Communities": 60,
    "Developer Communities": 70,
    "Sports Communities": 60,
    "Fitness Communities": 60,
    "Creator Communities": 70,
    "Book Communities": 50,
    "Gaming Communities": 50,
    "Travel Communities": 60,
    "Volunteer Groups": 120,
    "Meetups": 80,
    "Clubs": 60,
    "Online Communities": 40,
    "Neighborhoods": 50,
    "Community Projects": 180,
    "Fundraisers": 250,
    "Social Causes": 250,
    "Support Groups": 150,
    "Community Events": 100,
    "Community Stories": 80
  },
  "Cooking": {
    "Breakfast": 30,
    "Lunch": 30,
    "Dinner": 40,
    "Snacks": 20,
    "Soups": 40,
    "Salads": 30,
    "Grilling": 100,
    "Baking": 120,
    "Roasting": 80,
    "Frying": 60,
    "Air Fryer": 50,
    "Meal Prep": 100,
    "Sauces": 80,
    "Pasta Making": 100,
    "Bread Making": 120,
    "Pizza Making": 100,
    "Dessert Making": 100,
    "Fermentation": 180,
    "Pickling": 100,
    "Plating": 80
  },
  "Cricket": {
    "Test Cricket": 60,
    "ODI Cricket": 50,
    "T20 Cricket": 40,
    "IPL": 40,
    "International Cricket": 50,
    "Domestic Cricket": 40,
    "Club Cricket": 50,
    "Street Cricket": 20,
    "Batting": 100,
    "Bowling": 120,
    "Fielding": 100,
    "Wicketkeeping": 120,
    "Cricket Training": 120,
    "Cricket Gear": 30,
    "Cricket Grounds": 20,
    "Cricket Records": 80,
    "Cricket Tournaments": 120,
    "Match Highlights": 30,
    "Cricket Fans": 20,
    "Cricket News": 20
  },
  "Cycling": {
    "Road Cycling": 100,
    "Mountain Biking": 180,
    "City Cycling": 50,
    "Cycling Tours": 120,
    "Cycling Training": 120,
    "Cycling Fitness": 100,
    "Cycling Gear": 40,
    "Bicycle Maintenance": 80,
    "Cycling Safety": 80,
    "Cycling Routes": 60,
    "Cycling Challenges": 150,
    "Cycling Events": 80,
    "Cycling Communities": 50,
    "Cycling Photography": 40,
    "Long Rides": 180,
    "Commuting": 60,
    "Cycling Tips": 30,
    "Bike Reviews": 30,
    "Cycling Records": 100,
    "Cycling Adventures": 150
  },
  "Dance": {
    "Dance Ideas": 30,
    "Dance Stories": 30,
    "Dance Experiences": 50,
    "Dance Highlights": 40,
    "Dance Discoveries": 40,
    "Dance Recommendations": 30,
    "Dance Guides": 50,
    "Dance Collections": 30,
    "Dance Moments": 30,
    "Dance Events": 50,
    "Dance Trends": 30,
    "Dance Communities": 50,
    "Dance Projects": 100,
    "Dance Challenges": 100,
    "Dance Favorites": 20,
    "Dance Tips": 40,
    "Dance Reviews": 30,
    "Dance Inspiration": 40,
    "Dance News": 20,
    "Dance Showcase": 80
  },
  "Design": {
    "Design Ideas": 30,
    "Design Stories": 30,
    "Design Experiences": 50,
    "Design Highlights": 40,
    "Design Discoveries": 50,
    "Design Recommendations": 30,
    "Design Guides": 60,
    "Design Collections": 40,
    "Design Moments": 30,
    "Design Events": 50,
    "Design Trends": 40,
    "Design Communities": 50,
    "Design Projects": 120,
    "Design Challenges": 120,
    "Design Favorites": 20,
    "Design Tips": 50,
    "Design Reviews": 40,
    "Design Inspiration": 50,
    "Design News": 20,
    "Design Showcase": 80
  },
  "DIY": {
    "DIY Ideas": 30,
    "DIY Stories": 30,
    "DIY Experiences": 50,
    "DIY Highlights": 40,
    "DIY Discoveries": 50,
    "DIY Recommendations": 30,
    "DIY Guides": 60,
    "DIY Collections": 40,
    "DIY Moments": 30,
    "DIY Events": 40,
    "DIY Trends": 30,
    "DIY Communities": 50,
    "DIY Projects": 120,
    "DIY Challenges": 120,
    "DIY Favorites": 20,
    "DIY Tips": 40,
    "DIY Reviews": 30,
    "DIY Inspiration": 40,
    "DIY News": 20,
    "DIY Showcase": 80
  },
  "Education": {
    "Education Ideas": 30,
    "Education Stories": 30,
    "Education Experiences": 50,
    "Education Highlights": 40,
    "Education Discoveries": 70,
    "Education Recommendations": 30,
    "Education Guides": 70,
    "Education Collections": 40,
    "Education Moments": 30,
    "Education Events": 50,
    "Education Trends": 40,
    "Education Communities": 50,
    "Education Projects": 120,
    "Education Challenges": 100,
    "Education Favorites": 20,
    "Education Tips": 50,
    "Education Reviews": 40,
    "Education Inspiration": 50,
    "Education News": 30,
    "Education Showcase": 70
  },
  "Entrepreneurship": {
    "Entrepreneurship Ideas": 80,
    "Entrepreneurship Stories": 60,
    "Entrepreneurship Experiences": 100,
    "Entrepreneurship Highlights": 50,
    "Entrepreneurship Discoveries": 100,
    "Entrepreneurship Recommendations": 50,
    "Entrepreneurship Guides": 120,
    "Entrepreneurship Collections": 50,
    "Entrepreneurship Moments": 40,
    "Entrepreneurship Events": 70,
    "Entrepreneurship Trends": 50,
    "Entrepreneurship Communities": 70,
    "Entrepreneurship Projects": 150,
    "Entrepreneurship Challenges": 200,
    "Entrepreneurship Favorites": 30,
    "Entrepreneurship Tips": 70,
    "Entrepreneurship Reviews": 50,
    "Entrepreneurship Inspiration": 70,
    "Entrepreneurship News": 30,
    "Entrepreneurship Showcase": 100
  },
  "Events": {
    "Events Ideas": 30,
    "Events Stories": 30,
    "Events Experiences": 50,
    "Events Highlights": 40,
    "Events Discoveries": 40,
    "Events Recommendations": 30,
    "Events Guides": 50,
    "Events Collections": 30,
    "Events Moments": 30,
    "Events Events": 30,
    "Events Trends": 30,
    "Events Communities": 40,
    "Events Projects": 70,
    "Events Challenges": 80,
    "Events Favorites": 20,
    "Events Tips": 40,
    "Events Reviews": 30,
    "Events Inspiration": 40,
    "Events News": 20,
    "Events Showcase": 60
  },
  "Exercise": {
    "Push-Ups": 60,
    "Pull-Ups": 120,
    "Squats": 60,
    "Lunges": 70,
    "Plank": 70,
    "Burpees": 100,
    "Jump Rope": 80,
    "Running": 80,
    "Cycling": 70,
    "Swimming": 100,
    "Walking": 20,
    "Stretching": 30,
    "Yoga": 60,
    "HIIT": 120,
    "Weight Training": 120,
    "Core Workout": 80,
    "Leg Workout": 80,
    "Arm Workout": 70,
    "Full Body Workout": 120,
    "Mobility": 60
  },
  "Fashion": {
    "Casual Wear": 20,
    "Formal Wear": 40,
    "Streetwear": 40,
    "Athleisure": 30,
    "Party Wear": 40,
    "Traditional Wear": 50,
    "Office Wear": 40,
    "Summer Wear": 20,
    "Winter Wear": 30,
    "Denim": 20,
    "T-Shirts": 10,
    "Shirts": 20,
    "Jackets": 30,
    "Dresses": 30,
    "Suits": 50,
    "Ethnic Wear": 50,
    "Accessories": 20,
    "Watches": 30,
    "Bags": 20,
    "Footwear": 20
  },
  "Finance": {
    "Budgeting": 80,
    "Saving": 60,
    "Investing": 120,
    "Stocks": 150,
    "Mutual Funds": 100,
    "ETFs": 100,
    "Bonds": 80,
    "Retirement": 180,
    "Taxes": 150,
    "Credit Cards": 70,
    "Loans": 100,
    "Insurance": 100,
    "Emergency Fund": 100,
    "Expense Tracking": 60,
    "Passive Income": 150,
    "Side Income": 120,
    "Real Estate": 180,
    "Cryptocurrency": 150,
    "Financial Planning": 180,
    "Money Management": 120
  },
  "Fitness": {
    "Weightlifting": 150,
    "Powerlifting": 250,
    "Bodybuilding": 200,
    "Calisthenics": 180,
    "CrossFit": 180,
    "HIIT": 120,
    "Cardio": 80,
    "Cycling": 70,
    "Running": 80,
    "Swimming": 100,
    "Yoga": 60,
    "Pilates": 70,
    "Boxing": 150,
    "Kickboxing": 180,
    "Martial Arts": 220,
    "Mobility Training": 70,
    "Flexibility Training": 70,
    "Core Training": 80,
    "Functional Training": 100,
    "Sports Conditioning": 150
  },
  "Food": {
    "Noodles": 20,
    "Sushi": 250,
    "Ramen": 30,
    "Pizza": 20,
    "Burger": 20,
    "Tacos": 30,
    "Burritos": 30,
    "Sandwiches": 20,
    "Wraps": 20,
    "Dumplings": 30,
    "Fried Rice": 20,
    "Biryani": 30,
    "Curry": 30,
    "Steak": 60,
    "BBQ": 80,
    "Fried Chicken": 20,
    "Salads": 20,
    "Soups": 30,
    "Cheesecake": 30,
    "Ice Cream": 20
  },
  "Football": {
    "International Football": 250,
    "Premier League": 40,
    "La Liga": 40,
    "Champions League": 50,
    "World Cup": 150,
    "Indian Football": 300,
    "Football Players": 30,
    "Football Teams": 30,
    "Match Highlights": 30,
    "Football News": 20,
    "Dribbling": 100,
    "Passing": 80,
    "Shooting": 100,
    "Defending": 100,
    "Goalkeeping": 120,
    "Football Training": 120,
    "Football Gear": 30,
    "Football Tactics": 150,
    "Football History": 60,
    "Football Moments": 30
  },
  "Gaming": {
    "Action Games": 30,
    "RPG": 50,
    "FPS": 50,
    "Racing Games": 30,
    "Sports Games": 30,
    "Strategy Games": 60,
    "Simulation Games": 40,
    "Survival Games": 50,
    "Horror Games": 50,
    "Puzzle Games": 40,
    "Open World": 50,
    "Battle Royale": 40,
    "MOBA": 50,
    "Fighting Games": 50,
    "Platformers": 30,
    "Indie Games": 40,
    "Co-op Games": 40,
    "Mobile Games": 20,
    "PC Games": 20,
    "Console Games": 20
  },
  "Gardening": {
    "Gardening Ideas": 30,
    "Gardening Stories": 30,
    "Gardening Experiences": 50,
    "Gardening Highlights": 40,
    "Gardening Discoveries": 50,
    "Gardening Recommendations": 30,
    "Gardening Guides": 60,
    "Gardening Collections": 40,
    "Gardening Moments": 30,
    "Gardening Events": 40,
    "Gardening Trends": 30,
    "Gardening Communities": 50,
    "Gardening Projects": 100,
    "Gardening Challenges": 100,
    "Gardening Favorites": 20,
    "Gardening Tips": 40,
    "Gardening Reviews": 30,
    "Gardening Inspiration": 40,
    "Gardening News": 20,
    "Gardening Showcase": 70
  },
  "Goals": {
    "Goals Ideas": 30,
    "Goals Stories": 30,
    "Goals Experiences": 50,
    "Goals Highlights": 40,
    "Goals Discoveries": 50,
    "Goals Recommendations": 30,
    "Goals Guides": 60,
    "Goals Collections": 40,
    "Goals Moments": 30,
    "Goals Events": 40,
    "Goals Trends": 30,
    "Goals Communities": 40,
    "Goals Projects": 80,
    "Goals Challenges": 120,
    "Goals Favorites": 20,
    "Goals Tips": 40,
    "Goals Reviews": 30,
    "Goals Inspiration": 50,
    "Goals News": 20,
    "Goals Showcase": 70
  },
  "Hiking": {
    "Hiking Ideas": 30,
    "Hiking Stories": 40,
    "Hiking Experiences": 80,
    "Hiking Highlights": 50,
    "Hiking Discoveries": 70,
    "Hiking Recommendations": 40,
    "Hiking Guides": 80,
    "Hiking Collections": 40,
    "Hiking Moments": 30,
    "Hiking Events": 60,
    "Hiking Trends": 30,
    "Hiking Communities": 50,
    "Hiking Projects": 80,
    "Hiking Challenges": 150,
    "Hiking Favorites": 20,
    "Hiking Tips": 50,
    "Hiking Reviews": 40,
    "Hiking Inspiration": 50,
    "Hiking News": 20,
    "Hiking Showcase": 70
  },
  "History": {
    "History Ideas": 30,
    "History Stories": 40,
    "History Experiences": 40,
    "History Highlights": 50,
    "History Discoveries": 80,
    "History Recommendations": 30,
    "History Guides": 80,
    "History Collections": 50,
    "History Moments": 40,
    "History Events": 60,
    "History Trends": 30,
    "History Communities": 40,
    "History Projects": 100,
    "History Challenges": 100,
    "History Favorites": 20,
    "History Tips": 40,
    "History Reviews": 30,
    "History Inspiration": 50,
    "History News": 30,
    "History Showcase": 70
  },
  "Inspiration": {
    "Inspiration Ideas": 30,
    "Inspiration Stories": 50,
    "Inspiration Experiences": 60,
    "Inspiration Highlights": 40,
    "Inspiration Discoveries": 50,
    "Inspiration Recommendations": 30,
    "Inspiration Guides": 50,
    "Inspiration Collections": 40,
    "Inspiration Moments": 30,
    "Inspiration Events": 40,
    "Inspiration Trends": 30,
    "Inspiration Communities": 50,
    "Inspiration Projects": 80,
    "Inspiration Challenges": 100,
    "Inspiration Favorites": 20,
    "Inspiration Tips": 40,
    "Inspiration Reviews": 30,
    "Inspiration Inspiration": 30,
    "Inspiration News": 20,
    "Inspiration Showcase": 60
  },
  "Investing": {
    "Investing Ideas": 50,
    "Investing Stories": 40,
    "Investing Experiences": 60,
    "Investing Highlights": 40,
    "Investing Discoveries": 100,
    "Investing Recommendations": 60,
    "Investing Guides": 120,
    "Investing Collections": 50,
    "Investing Moments": 30,
    "Investing Events": 50,
    "Investing Trends": 50,
    "Investing Communities": 60,
    "Investing Projects": 100,
    "Investing Challenges": 150,
    "Investing Favorites": 30,
    "Investing Tips": 70,
    "Investing Reviews": 60,
    "Investing Inspiration": 40,
    "Investing News": 30,
    "Investing Showcase": 60
  },
  "Journaling": {
    "Journaling Ideas": 30,
    "Journaling Stories": 40,
    "Journaling Experiences": 50,
    "Journaling Highlights": 30,
    "Journaling Discoveries": 50,
    "Journaling Recommendations": 30,
    "Journaling Guides": 50,
    "Journaling Collections": 40,
    "Journaling Moments": 30,
    "Journaling Events": 30,
    "Journaling Trends": 30,
    "Journaling Communities": 40,
    "Journaling Projects": 80,
    "Journaling Challenges": 100,
    "Journaling Favorites": 20,
    "Journaling Tips": 40,
    "Journaling Reviews": 30,
    "Journaling Inspiration": 40,
    "Journaling News": 20,
    "Journaling Showcase": 60
  },
  "Knowledge": {
    "Knowledge Ideas": 30,
    "Knowledge Stories": 40,
    "Knowledge Experiences": 50,
    "Knowledge Highlights": 40,
    "Knowledge Discoveries": 100,
    "Knowledge Recommendations": 30,
    "Knowledge Guides": 70,
    "Knowledge Collections": 60,
    "Knowledge Moments": 30,
    "Knowledge Events": 40,
    "Knowledge Trends": 30,
    "Knowledge Communities": 50,
    "Knowledge Projects": 100,
    "Knowledge Challenges": 120,
    "Knowledge Favorites": 20,
    "Knowledge Tips": 50,
    "Knowledge Reviews": 30,
    "Knowledge Inspiration": 50,
    "Knowledge News": 30,
    "Knowledge Showcase": 70
  },
  "Learning": {
    "Learning Ideas": 30,
    "Learning Stories": 40,
    "Learning Experiences": 50,
    "Learning Highlights": 40,
    "Learning Discoveries": 100,
    "Learning Recommendations": 30,
    "Learning Guides": 70,
    "Learning Collections": 50,
    "Learning Moments": 30,
    "Learning Events": 40,
    "Learning Trends": 30,
    "Learning Communities": 50,
    "Learning Projects": 100,
    "Learning Challenges": 120,
    "Learning Favorites": 20,
    "Learning Tips": 50,
    "Learning Reviews": 30,
    "Learning Inspiration": 50,
    "Learning News": 30,
    "Learning Showcase": 70
  },
  "Life Lessons": {
    "Life Lessons Ideas": 40,
    "Life Lessons Stories": 80,
    "Life Lessons Experiences": 100,
    "Life Lessons Highlights": 50,
    "Life Lessons Discoveries": 100,
    "Life Lessons Recommendations": 40,
    "Life Lessons Guides": 100,
    "Life Lessons Collections": 50,
    "Life Lessons Moments": 60,
    "Life Lessons Events": 40,
    "Life Lessons Trends": 30,
    "Life Lessons Communities": 50,
    "Life Lessons Projects": 100,
    "Life Lessons Challenges": 150,
    "Life Lessons Favorites": 20,
    "Life Lessons Tips": 70,
    "Life Lessons Reviews": 40,
    "Life Lessons Inspiration": 80,
    "Life Lessons News": 30,
    "Life Lessons Showcase": 80
  },
  "Lifestyle": {
    "Lifestyle Ideas": 30,
    "Lifestyle Stories": 40,
    "Lifestyle Experiences": 60,
    "Lifestyle Highlights": 40,
    "Lifestyle Discoveries": 50,
    "Lifestyle Recommendations": 30,
    "Lifestyle Guides": 60,
    "Lifestyle Collections": 40,
    "Lifestyle Moments": 30,
    "Lifestyle Events": 40,
    "Lifestyle Trends": 30,
    "Lifestyle Communities": 50,
    "Lifestyle Projects": 80,
    "Lifestyle Challenges": 100,
    "Lifestyle Favorites": 20,
    "Lifestyle Tips": 40,
    "Lifestyle Reviews": 30,
    "Lifestyle Inspiration": 50,
    "Lifestyle News": 20,
    "Lifestyle Showcase": 60
  },
  "Meditation": {
    "Meditation Ideas": 30,
    "Meditation Stories": 40,
    "Meditation Experiences": 70,
    "Meditation Highlights": 40,
    "Meditation Discoveries": 60,
    "Meditation Recommendations": 30,
    "Meditation Guides": 70,
    "Meditation Collections": 40,
    "Meditation Moments": 50,
    "Meditation Events": 40,
    "Meditation Trends": 30,
    "Meditation Communities": 50,
    "Meditation Projects": 80,
    "Meditation Challenges": 120,
    "Meditation Favorites": 20,
    "Meditation Tips": 50,
    "Meditation Reviews": 30,
    "Meditation Inspiration": 50,
    "Meditation News": 20,
    "Meditation Showcase": 60
  },
  "Movies": {
    "Action": 30,
    "Comedy": 20,
    "Drama": 30,
    "Thriller": 40,
    "Horror": 40,
    "Romance": 20,
    "Sci-Fi": 50,
    "Fantasy": 50,
    "Animation": 30,
    "Documentary": 60,
    "Mystery": 40,
    "Crime": 50,
    "Adventure": 40,
    "Biography": 60,
    "Historical": 70,
    "Superhero": 30,
    "Psychological": 80,
    "Indie Films": 50,
    "Short Films": 40,
    "Movie Classics": 50
  },
  "Music": {
    "Pop": 20,
    "Rock": 30,
    "Hip Hop": 30,
    "Rap": 30,
    "R&B": 30,
    "Jazz": 50,
    "Blues": 50,
    "Classical": 70,
    "Electronic": 30,
    "EDM": 30,
    "Indie": 30,
    "Lo-fi": 20,
    "Metal": 40,
    "Punk": 40,
    "Reggae": 40,
    "Country": 30,
    "K-Pop": 30,
    "Bollywood Music": 20,
    "Instrumental": 40,
    "Live Music": 50
  },
  "Nature": {
    "Forests": 50,
    "Mountains": 70,
    "Rivers": 40,
    "Lakes": 40,
    "Beaches": 30,
    "Waterfalls": 50,
    "Deserts": 60,
    "Islands": 70,
    "Wildlife": 150,
    "Birdwatching": 70,
    "Sunsets": 20,
    "Sunrises": 20,
    "Flowers": 20,
    "Trees": 30,
    "Gardens": 20,
    "National Parks": 80,
    "Hiking Trails": 70,
    "Weather": 30,
    "Seasons": 20,
    "Stargazing": 60
  },
  "Photography": {
    "Portraits": 80,
    "Street Photography": 100,
    "Landscape Photography": 80,
    "Wildlife Photography": 250,
    "Food Photography": 50,
    "Product Photography": 70,
    "Travel Photography": 80,
    "Astrophotography": 200,
    "Sports Photography": 150,
    "Architecture Photography": 100,
    "Macro Photography": 120,
    "Night Photography": 120,
    "Long Exposure": 150,
    "Black & White": 60,
    "Mobile Photography": 30,
    "Film Photography": 100,
    "Event Photography": 70,
    "Wedding Photography": 120,
    "Drone Photography": 150,
    "Self Portraits": 50
  },
  "Podcasts": {
    "Podcasts Ideas": 30,
    "Podcasts Stories": 40,
    "Podcasts Experiences": 50,
    "Podcasts Highlights": 30,
    "Podcasts Discoveries": 50,
    "Podcasts Recommendations": 30,
    "Podcasts Guides": 50,
    "Podcasts Collections": 40,
    "Podcasts Moments": 30,
    "Podcasts Events": 40,
    "Podcasts Trends": 30,
    "Podcasts Communities": 50,
    "Podcasts Projects": 80,
    "Podcasts Challenges": 100,
    "Podcasts Favorites": 20,
    "Podcasts Tips": 40,
    "Podcasts Reviews": 30,
    "Podcasts Inspiration": 40,
    "Podcasts News": 20,
    "Podcasts Showcase": 60
  },
  "Productivity": {
    "Deep Work": 150,
    "Time Blocking": 100,
    "Pomodoro": 60,
    "Task Lists": 40,
    "Priority Setting": 80,
    "Focus Sessions": 100,
    "Weekly Planning": 80,
    "Daily Planning": 50,
    "Calendar Blocking": 70,
    "Note Taking": 40,
    "Inbox Zero": 80,
    "Workspace Setup": 50,
    "Distraction Blocking": 100,
    "Automation": 120,
    "Routine Building": 100,
    "Goal Tracking": 80,
    "Project Planning": 120,
    "Meeting Management": 80,
    "Energy Management": 100,
    "Procrastination Control": 150
  },
  "Programming": {
    "HTML": 40,
    "CSS": 50,
    "JavaScript": 100,
    "TypeScript": 120,
    "Python": 100,
    "Java": 120,
    "C": 120,
    "C++": 150,
    "C#": 120,
    "Go": 130,
    "Rust": 180,
    "PHP": 90,
    "Swift": 120,
    "Kotlin": 120,
    "React": 120,
    "React Native": 150,
    "Node.js": 130,
    "Django": 140,
    "Flutter": 130,
    "SQL": 100
  },
  "Psychology": {
    "Psychology Ideas": 40,
    "Psychology Stories": 40,
    "Psychology Experiences": 60,
    "Psychology Highlights": 40,
    "Psychology Discoveries": 100,
    "Psychology Recommendations": 40,
    "Psychology Guides": 80,
    "Psychology Collections": 50,
    "Psychology Moments": 30,
    "Psychology Events": 40,
    "Psychology Trends": 30,
    "Psychology Communities": 50,
    "Psychology Projects": 120,
    "Psychology Challenges": 150,
    "Psychology Favorites": 20,
    "Psychology Tips": 60,
    "Psychology Reviews": 40,
    "Psychology Inspiration": 50,
    "Psychology News": 30,
    "Psychology Showcase": 70
  },
  "Relationships": {
    "Relationships Ideas": 40,
    "Relationships Stories": 60,
    "Relationships Experiences": 80,
    "Relationships Highlights": 40,
    "Relationships Discoveries": 60,
    "Relationships Recommendations": 40,
    "Relationships Guides": 80,
    "Relationships Collections": 40,
    "Relationships Moments": 50,
    "Relationships Events": 40,
    "Relationships Trends": 30,
    "Relationships Communities": 50,
    "Relationships Projects": 80,
    "Relationships Challenges": 150,
    "Relationships Favorites": 20,
    "Relationships Tips": 70,
    "Relationships Reviews": 40,
    "Relationships Inspiration": 60,
    "Relationships News": 20,
    "Relationships Showcase": 70
  },
  "Running": {
    "Jogging": 40,
    "Sprint": 100,
    "Long Distance": 150,
    "Marathon": 350,
    "Half Marathon": 250,
    "Trail Running": 180,
    "Running Training": 120,
    "Running Shoes": 30,
    "Running Routes": 40,
    "Running Fitness": 100,
    "Running Challenges": 180,
    "Running Events": 100,
    "Running Safety": 60,
    "Running Nutrition": 80,
    "Running Recovery": 80,
    "Running Records": 250,
    "Running Motivation": 40,
    "Running Communities": 40,
    "Running Tips": 40,
    "Running Stories": 50
  },
  "Science": {
    "Science Ideas": 30,
    "Science Stories": 40,
    "Science Experiences": 50,
    "Science Highlights": 40,
    "Science Discoveries": 120,
    "Science Recommendations": 30,
    "Science Guides": 80,
    "Science Collections": 50,
    "Science Moments": 30,
    "Science Events": 50,
    "Science Trends": 40,
    "Science Communities": 50,
    "Science Projects": 150,
    "Science Challenges": 150,
    "Science Favorites": 20,
    "Science Tips": 50,
    "Science Reviews": 40,
    "Science Inspiration": 50,
    "Science News": 30,
    "Science Showcase": 80
  },
  "Self Improvement": {
    "Confidence": 120,
    "Discipline": 150,
    "Consistency": 150,
    "Communication": 100,
    "Time Management": 100,
    "Focus": 120,
    "Emotional Intelligence": 180,
    "Decision Making": 150,
    "Public Speaking": 180,
    "Leadership": 200,
    "Problem Solving": 150,
    "Critical Thinking": 180,
    "Self Awareness": 150,
    "Resilience": 200,
    "Courage": 200,
    "Patience": 100,
    "Accountability": 150,
    "Positive Thinking": 80,
    "Personal Boundaries": 150,
    "Growth Mindset": 120
  },
  "Skincare": {
    "Skincare Ideas": 20,
    "Skincare Stories": 30,
    "Skincare Experiences": 40,
    "Skincare Highlights": 30,
    "Skincare Discoveries": 60,
    "Skincare Recommendations": 30,
    "Skincare Guides": 70,
    "Skincare Collections": 40,
    "Skincare Moments": 20,
    "Skincare Events": 30,
    "Skincare Trends": 30,
    "Skincare Communities": 40,
    "Skincare Projects": 70,
    "Skincare Challenges": 80,
    "Skincare Favorites": 20,
    "Skincare Tips": 50,
    "Skincare Reviews": 40,
    "Skincare Inspiration": 40,
    "Skincare News": 20,
    "Skincare Showcase": 60
  },
  "Sleep": {
    "Sleep Ideas": 20,
    "Sleep Stories": 30,
    "Sleep Experiences": 40,
    "Sleep Highlights": 30,
    "Sleep Discoveries": 50,
    "Sleep Recommendations": 30,
    "Sleep Guides": 60,
    "Sleep Collections": 40,
    "Sleep Moments": 20,
    "Sleep Events": 30,
    "Sleep Trends": 20,
    "Sleep Communities": 40,
    "Sleep Projects": 60,
    "Sleep Challenges": 100,
    "Sleep Favorites": 20,
    "Sleep Tips": 50,
    "Sleep Reviews": 30,
    "Sleep Inspiration": 40,
    "Sleep News": 20,
    "Sleep Showcase": 50
  },
  "Space": {
    "Space Ideas": 30,
    "Space Stories": 40,
    "Space Experiences": 50,
    "Space Highlights": 40,
    "Space Discoveries": 100,
    "Space Recommendations": 30,
    "Space Guides": 70,
    "Space Collections": 50,
    "Space Moments": 30,
    "Space Events": 50,
    "Space Trends": 40,
    "Space Communities": 50,
    "Space Projects": 120,
    "Space Challenges": 150,
    "Space Favorites": 20,
    "Space Tips": 50,
    "Space Reviews": 30,
    "Space Inspiration": 50,
    "Space News": 30,
    "Space Showcase": 80
  },
  "Spirituality": {
    "Spirituality Ideas": 30,
    "Spirituality Stories": 50,
    "Spirituality Experiences": 80,
    "Spirituality Highlights": 40,
    "Spirituality Discoveries": 70,
    "Spirituality Recommendations": 30,
    "Spirituality Guides": 70,
    "Spirituality Collections": 40,
    "Spirituality Moments": 50,
    "Spirituality Events": 40,
    "Spirituality Trends": 30,
    "Spirituality Communities": 50,
    "Spirituality Projects": 80,
    "Spirituality Challenges": 120,
    "Spirituality Favorites": 20,
    "Spirituality Tips": 50,
    "Spirituality Reviews": 30,
    "Spirituality Inspiration": 70,
    "Spirituality News": 20,
    "Spirituality Showcase": 60
  },
  "Study": {
    "Study Ideas": 30,
    "Study Stories": 40,
    "Study Experiences": 50,
    "Study Highlights": 40,
    "Study Discoveries": 60,
    "Study Recommendations": 30,
    "Study Guides": 70,
    "Study Collections": 40,
    "Study Moments": 30,
    "Study Events": 40,
    "Study Trends": 30,
    "Study Communities": 50,
    "Study Projects": 100,
    "Study Challenges": 120,
    "Study Favorites": 20,
    "Study Tips": 50,
    "Study Reviews": 30,
    "Study Inspiration": 50,
    "Study News": 20,
    "Study Showcase": 60
  },
  "Swimming": {
    "Freestyle": 100,
    "Backstroke": 100,
    "Breaststroke": 100,
    "Butterfly": 150,
    "Swimming Training": 120,
    "Swimming Fitness": 100,
    "Open Water Swimming": 250,
    "Competitive Swimming": 200,
    "Swimming Techniques": 120,
    "Swimming Safety": 80,
    "Swimming Gear": 30,
    "Swimming Pools": 20,
    "Swimming Workouts": 100,
    "Swimming Challenges": 150,
    "Swimming Events": 80,
    "Swimming Records": 250,
    "Swimming Tips": 40,
    "Swimming Recovery": 60,
    "Swimming Communities": 40,
    "Swimming Stories": 50
  },
  "Technology": {
    "Smartphones": 30,
    "Laptops": 40,
    "Tablets": 30,
    "Smartwatches": 30,
    "Wireless Earbuds": 20,
    "Gaming Consoles": 30,
    "Cameras": 50,
    "Drones": 100,
    "Smart TVs": 20,
    "VR Headsets": 100,
    "AI": 150,
    "Robotics": 180,
    "3D Printers": 120,
    "Smart Home": 80,
    "Wearables": 50,
    "Electric Vehicles": 100,
    "Cloud Computing": 150,
    "Blockchain": 150,
    "AR/VR": 120,
    "Internet of Things": 150
  },
  "Tennis": {
    "Singles": 80,
    "Doubles": 70,
    "Grand Slams": 70,
    "ATP": 30,
    "WTA": 30,
    "Tennis Players": 30,
    "Tennis Teams": 30,
    "Match Highlights": 30,
    "Tennis News": 20,
    "Serving": 100,
    "Forehand": 80,
    "Backhand": 80,
    "Volleys": 100,
    "Tennis Training": 120,
    "Tennis Fitness": 100,
    "Tennis Gear": 30,
    "Tennis Courts": 20,
    "Tennis Tactics": 150,
    "Tennis History": 60,
    "Tennis Moments": 30
  },
  "Travel": {
    "City Trips": 50,
    "Beach Trips": 50,
    "Mountain Trips": 70,
    "Forest Trips": 70,
    "Desert Trips": 80,
    "Island Trips": 100,
    "Road Trips": 120,
    "Train Trips": 60,
    "Backpacking": 180,
    "Solo Travel": 200,
    "Family Trips": 80,
    "Luxury Travel": 100,
    "Budget Travel": 70,
    "Adventure Travel": 180,
    "Food Trips": 70,
    "Wildlife Trips": 150,
    "Cultural Trips": 120,
    "Weekend Getaways": 50,
    "Hidden Places": 120,
    "International Trips": 150
  },
  "Volunteering": {
    "Volunteering Ideas": 40,
    "Volunteering Stories": 60,
    "Volunteering Experiences": 100,
    "Volunteering Highlights": 50,
    "Volunteering Discoveries": 60,
    "Volunteering Recommendations": 40,
    "Volunteering Guides": 70,
    "Volunteering Collections": 40,
    "Volunteering Moments": 50,
    "Volunteering Events": 80,
    "Volunteering Trends": 30,
    "Volunteering Communities": 60,
    "Volunteering Projects": 180,
    "Volunteering Challenges": 200,
    "Volunteering Favorites": 20,
    "Volunteering Tips": 50,
    "Volunteering Reviews": 40,
    "Volunteering Inspiration": 70,
    "Volunteering News": 30,
    "Volunteering Showcase": 80
  },
  "Walking": {
    "Walking Ideas": 20,
    "Walking Stories": 30,
    "Walking Experiences": 40,
    "Walking Highlights": 30,
    "Walking Discoveries": 40,
    "Walking Recommendations": 20,
    "Walking Guides": 40,
    "Walking Collections": 30,
    "Walking Moments": 20,
    "Walking Events": 40,
    "Walking Trends": 20,
    "Walking Communities": 30,
    "Walking Projects": 60,
    "Walking Challenges": 100,
    "Walking Favorites": 10,
    "Walking Tips": 30,
    "Walking Reviews": 20,
    "Walking Inspiration": 30,
    "Walking News": 20,
    "Walking Showcase": 50
  },
  "Wellness": {
    "Sleep": 30,
    "Hydration": 20,
    "Nutrition": 50,
    "Walking": 20,
    "Meditation": 60,
    "Breathing": 40,
    "Stretching": 30,
    "Rest Days": 30,
    "Stress Relief": 70,
    "Mindfulness": 70,
    "Digital Detox": 120,
    "Self Care": 50,
    "Recovery": 80,
    "Healthy Routines": 70,
    "Sunlight": 30,
    "Outdoor Time": 40,
    "Relaxation": 40,
    "Work-Life Balance": 100,
    "Healthy Habits": 60,
    "Wellbeing": 70
  },
  "Writing": {
    "Writing Ideas": 30,
    "Writing Stories": 40,
    "Writing Experiences": 50,
    "Writing Highlights": 30,
    "Writing Discoveries": 40,
    "Writing Recommendations": 30,
    "Writing Guides": 60,
    "Writing Collections": 40,
    "Writing Moments": 30,
    "Writing Events": 40,
    "Writing Trends": 30,
    "Writing Communities": 50,
    "Writing Projects": 100,
    "Writing Challenges": 120,
    "Writing Favorites": 20,
    "Writing Tips": 50,
    "Writing Reviews": 30,
    "Writing Inspiration": 50,
    "Writing News": 20,
    "Writing Showcase": 70
  },
  "Yoga": {
    "Hatha Yoga": 70,
    "Vinyasa Yoga": 90,
    "Ashtanga Yoga": 120,
    "Power Yoga": 100,
    "Yin Yoga": 70,
    "Kundalini Yoga": 100,
    "Restorative Yoga": 60,
    "Bikram Yoga": 120,
    "Hot Yoga": 100,
    "Prenatal Yoga": 80,
    "Morning Yoga": 40,
    "Evening Yoga": 40,
    "Yoga Flow": 70,
    "Balance Poses": 100,
    "Inversion Poses": 180,
    "Backbend Poses": 150,
    "Hip Opening": 80,
    "Flexibility": 70,
    "Breathwork": 70,
    "Meditation": 60
  },
  "Career Growth": {
    "Promotions": 250,
    "Skill Development": 150,
    "Leadership Growth": 250,
    "Networking": 100,
    "Mentorship": 100,
    "Performance": 150,
    "Career Planning": 120,
    "Professional Branding": 120,
    "Communication": 100,
    "Management Skills": 180,
    "Technical Skills": 180,
    "Soft Skills": 100,
    "Career Goals": 100,
    "Workplace Learning": 100,
    "Job Opportunities": 80,
    "Career Transitions": 200,
    "Salary Growth": 250,
    "Work-Life Balance": 100,
    "Professional Achievements": 250,
    "Career Strategy": 200
  },
  "First Job": {
    "Job Search": 80,
    "Resume": 60,
    "Interview Preparation": 100,
    "First Day": 100,
    "Workplace Skills": 100,
    "Communication": 80,
    "Office Etiquette": 50,
    "Time Management": 80,
    "Teamwork": 80,
    "Learning at Work": 100,
    "Mentorship": 100,
    "Performance": 150,
    "Salary": 120,
    "Benefits": 60,
    "Workplace Relationships": 80,
    "Career Goals": 100,
    "Professional Growth": 150,
    "Common Mistakes": 50,
    "First Job Stories": 60,
    "First Job Tips": 50
  },
  "Internship": {
    "Finding Internships": 80,
    "Resume": 60,
    "Applications": 70,
    "Interviews": 100,
    "Onboarding": 50,
    "Intern Projects": 150,
    "Mentorship": 100,
    "Workplace Skills": 100,
    "Technical Skills": 150,
    "Communication": 80,
    "Teamwork": 80,
    "Time Management": 80,
    "Learning": 100,
    "Internship Challenges": 150,
    "Internship Achievements": 200,
    "Internship Reviews": 50,
    "Internship Tips": 50,
    "Internship Stories": 60,
    "PPO": 300,
    "Career Preparation": 120
  },
  "Exams": {
    "Exam Preparation": 100,
    "Study Plans": 80,
    "Revision": 70,
    "Practice Tests": 100,
    "Mock Exams": 120,
    "Notes": 40,
    "Time Management": 80,
    "Memory Techniques": 80,
    "Focus": 100,
    "Exam Anxiety": 60,
    "Subject Strategies": 100,
    "Previous Papers": 70,
    "Group Study": 50,
    "Online Resources": 40,
    "Last-Minute Revision": 60,
    "Exam Day Tips": 30,
    "Results": 40,
    "Competitive Exams": 150,
    "College Exams": 100,
    "School Exams": 70
  },
  "Graduation": {
    "Graduation Ceremony": 100,
    "Degree": 150,
    "Convocation": 150,
    "Graduation Photos": 40,
    "Graduation Memories": 60,
    "Friends": 30,
    "Family": 40,
    "Achievements": 100,
    "Projects": 100,
    "Placements": 200,
    "First Job": 200,
    "Higher Studies": 150,
    "Career Planning": 120,
    "Graduation Events": 70,
    "Graduation Speeches": 100,
    "Graduation Gifts": 30,
    "Graduation Travel": 100,
    "Alumni": 80,
    "Post-Graduation Life": 150,
    "Graduation Stories": 60
  },
  "New Skills": {
    "Programming": 120,
    "Communication": 100,
    "Public Speaking": 180,
    "Cooking": 80,
    "Photography": 100,
    "Design": 100,
    "Writing": 80,
    "Languages": 180,
    "Fitness": 100,
    "Music": 120,
    "Art": 100,
    "Leadership": 180,
    "Time Management": 80,
    "Financial Skills": 120,
    "Digital Skills": 100,
    "Creative Skills": 100,
    "Problem Solving": 150,
    "Research": 120,
    "Presentation Skills": 120,
    "Learning Strategies": 100
  },
  "Certifications": {
    "Academic Wins": 150,
    "Career Wins": 250,
    "Sports Wins": 150,
    "Fitness Milestones": 100,
    "Project Completion": 100,
    "Competition Wins": 250,
    "Certifications": 150,
    "First-Time Achievements": 200,
    "Personal Records": 250,
    "Financial Milestones": 300,
    "Creative Achievements": 150,
    "Skill Milestones": 150,
    "Habit Streaks": 100,
    "Goal Completion": 150,
    "Overcoming Fear": 250,
    "Major Life Milestones": 400,
    "Team Achievements": 150,
    "Community Impact": 300,
    "Comeback Stories": 350,
    "Milestone Unlocked": 200
  },
  "Projects": {
    "College Projects": 100,
    "Personal Projects": 120,
    "Team Projects": 120,
    "Coding Projects": 150,
    "Research Projects": 180,
    "Creative Projects": 120,
    "Startup Projects": 250,
    "Open Source": 200,
    "Hackathons": 250,
    "Project Ideas": 30,
    "Project Planning": 80,
    "Project Management": 150,
    "Project Tools": 40,
    "Project Documentation": 70,
    "Project Demos": 100,
    "Project Challenges": 150,
    "Project Achievements": 200,
    "Project Reviews": 50,
    "Project Collaboration": 100,
    "Project Lessons": 80
  },
  "Hackathons": {
    "Hackathon Ideas": 40,
    "Team Formation": 80,
    "Problem Statements": 100,
    "Coding": 150,
    "Design": 100,
    "Prototyping": 120,
    "AI Projects": 200,
    "Web Projects": 150,
    "Mobile Projects": 150,
    "Hardware Projects": 220,
    "Presentations": 100,
    "Pitching": 150,
    "Mentorship": 80,
    "Judging": 80,
    "Hackathon Winners": 400,
    "Hackathon Tips": 50,
    "Hackathon Stories": 70,
    "Hackathon Events": 50,
    "Open Source Hackathons": 250,
    "Hackathon Resources": 50
  },
  "Public Speaking": {
    "Presentations": 100,
    "Speeches": 120,
    "Debates": 150,
    "Storytelling": 100,
    "Interviews": 100,
    "Group Discussions": 100,
    "Stage Confidence": 150,
    "Body Language": 80,
    "Voice Control": 100,
    "Communication Skills": 100,
    "Presentation Design": 70,
    "Speaking Practice": 60,
    "Impromptu Speaking": 180,
    "Professional Speaking": 150,
    "Academic Speaking": 100,
    "Public Speaking Tips": 50,
    "Common Mistakes": 30,
    "Speech Writing": 80,
    "Speaking Events": 70,
    "Speaker Stories": 60
  },
  "Leadership": {
    "Team Leadership": 180,
    "Student Leadership": 120,
    "Workplace Leadership": 200,
    "Decision Making": 150,
    "Delegation": 150,
    "Communication": 100,
    "Motivation": 100,
    "Conflict Resolution": 180,
    "Mentoring": 120,
    "Planning": 100,
    "Strategy": 180,
    "Accountability": 150,
    "Team Building": 150,
    "Leadership Skills": 150,
    "Leadership Stories": 60,
    "Leadership Lessons": 100,
    "Leadership Challenges": 200,
    "Leadership Books": 50,
    "Leadership Events": 60,
    "Leadership Growth": 200
  },
  "Teamwork": {
    "Collaboration": 100,
    "Communication": 80,
    "Team Roles": 70,
    "Trust": 100,
    "Problem Solving": 120,
    "Conflict Resolution": 150,
    "Team Projects": 120,
    "Team Building": 120,
    "Leadership": 150,
    "Delegation": 120,
    "Feedback": 80,
    "Group Goals": 80,
    "Remote Teams": 100,
    "Student Teams": 60,
    "Work Teams": 80,
    "Sports Teams": 70,
    "Creative Teams": 80,
    "Team Challenges": 150,
    "Team Success": 150,
    "Team Lessons": 80
  },
  "Travel Tips": {
    "Packing": 30,
    "Budget Travel": 70,
    "Travel Safety": 100,
    "Planning": 70,
    "Flights": 40,
    "Trains": 30,
    "Hotels": 40,
    "Hostels": 40,
    "Travel Apps": 30,
    "Travel Documents": 60,
    "Local Transport": 50,
    "Food Travel": 50,
    "Solo Travel": 150,
    "Family Travel": 70,
    "Student Travel": 70,
    "Photography": 40,
    "Travel Insurance": 60,
    "Travel Planning": 80,
    "Travel Hacks": 40,
    "Travel Mistakes": 50
  },
  "Road Trips": {
    "Route Planning": 60,
    "Road Trip Essentials": 40,
    "Car Travel": 50,
    "Bike Trips": 100,
    "Highways": 30,
    "Scenic Routes": 50,
    "Roadside Food": 30,
    "Road Safety": 80,
    "Travel Budgets": 60,
    "Road Trip Music": 20,
    "Camping Trips": 120,
    "Weekend Road Trips": 70,
    "Long Drives": 120,
    "Road Trip Photography": 50,
    "Road Trip Stops": 30,
    "Maps": 40,
    "Travel Companions": 40,
    "Road Trip Stories": 50,
    "Road Trip Tips": 40,
    "Road Trip Challenges": 150
  },
  "Camping": {
    "Tent Camping": 100,
    "Backpacking": 180,
    "Car Camping": 70,
    "Family Camping": 80,
    "Solo Camping": 180,
    "Mountain Camping": 150,
    "Forest Camping": 120,
    "Beach Camping": 120,
    "Camping Gear": 50,
    "Camp Cooking": 80,
    "Campfire": 60,
    "Hiking": 100,
    "Camping Safety": 100,
    "Wildlife Safety": 150,
    "Camping Locations": 60,
    "Camping Tips": 40,
    "Camping Photography": 50,
    "Camping Challenges": 150,
    "Camping Stories": 60,
    "Camping Essentials": 40
  },
  "Street Food": {
    "Indian Street Food": 30,
    "Asian Street Food": 40,
    "Middle Eastern Street Food": 50,
    "European Street Food": 50,
    "Snacks": 20,
    "Chaat": 20,
    "Rolls": 20,
    "Sandwiches": 20,
    "Noodles": 20,
    "Grilled Food": 40,
    "Fried Food": 20,
    "Desserts": 20,
    "Drinks": 20,
    "Food Stalls": 30,
    "Food Markets": 40,
    "Street Food Reviews": 30,
    "Street Food Photography": 30,
    "Street Food Tours": 70,
    "Local Specialties": 40,
    "Food Recommendations": 20
  },
  "Recipes": {
    "Breakfast Recipes": 30,
    "Lunch Recipes": 30,
    "Dinner Recipes": 40,
    "Snack Recipes": 20,
    "Dessert Recipes": 30,
    "Indian Recipes": 30,
    "Asian Recipes": 40,
    "Italian Recipes": 40,
    "Mexican Recipes": 40,
    "Healthy Recipes": 50,
    "Vegetarian Recipes": 30,
    "Vegan Recipes": 40,
    "Quick Recipes": 20,
    "Easy Recipes": 20,
    "Baking Recipes": 100,
    "Drinks": 20,
    "Meal Prep": 80,
    "Family Recipes": 50,
    "Recipe Reviews": 20,
    "Recipe Ideas": 20
  },
  "Restaurants": {
    "Restaurant Reviews": 30,
    "Fine Dining": 70,
    "Cafes": 20,
    "Fast Food": 20,
    "Family Restaurants": 30,
    "Indian Restaurants": 30,
    "Italian Restaurants": 30,
    "Asian Restaurants": 30,
    "Vegetarian Restaurants": 30,
    "Vegan Restaurants": 40,
    "Street Food Restaurants": 30,
    "Dessert Places": 20,
    "Breakfast Places": 20,
    "Lunch Places": 20,
    "Dinner Places": 30,
    "Restaurant Recommendations": 20,
    "Restaurant Photography": 30,
    "New Restaurants": 30,
    "Restaurant Offers": 10,
    "Dining Experiences": 50
  },
  "Sports Moments": {
    "Match Highlights": 30,
    "Winning Moments": 50,
    "Great Goals": 50,
    "Great Plays": 50,
    "Records": 100,
    "Comebacks": 120,
    "Championships": 150,
    "Celebrations": 40,
    "Team Moments": 40,
    "Fan Moments": 30,
    "Historic Matches": 100,
    "Sportsmanship": 100,
    "Athlete Stories": 60,
    "Viral Sports Moments": 30,
    "Funny Sports Moments": 20,
    "Emotional Sports Moments": 40,
    "Training Moments": 40,
    "Behind the Scenes": 40,
    "Sports Memories": 30,
    "Sports Reactions": 20
  },
  "Memes": {
    "Memes Ideas": 20,
    "Memes Stories": 20,
    "Memes Experiences": 20,
    "Memes Highlights": 20,
    "Memes Discoveries": 20,
    "Memes Recommendations": 10,
    "Memes Guides": 20,
    "Memes Collections": 20,
    "Memes Moments": 20,
    "Memes Events": 20,
    "Memes Trends": 20,
    "Memes Communities": 30,
    "Memes Projects": 40,
    "Memes Challenges": 50,
    "Memes Favorites": 10,
    "Memes Tips": 20,
    "Memes Reviews": 10,
    "Memes Inspiration": 20,
    "Memes News": 10,
    "Memes Showcase": 40
  },
  "Funny Moments": {
    "Funny Moments Ideas": 20,
    "Funny Moments Stories": 30,
    "Funny Moments Experiences": 30,
    "Funny Moments Highlights": 20,
    "Funny Moments Discoveries": 20,
    "Funny Moments Recommendations": 10,
    "Funny Moments Guides": 20,
    "Funny Moments Collections": 20,
    "Funny Moments Moments": 20,
    "Funny Moments Events": 20,
    "Funny Moments Trends": 20,
    "Funny Moments Communities": 30,
    "Funny Moments Projects": 40,
    "Funny Moments Challenges": 50,
    "Funny Moments Favorites": 10,
    "Funny Moments Tips": 20,
    "Funny Moments Reviews": 10,
    "Funny Moments Inspiration": 20,
    "Funny Moments News": 10,
    "Funny Moments Showcase": 40
  },
  "Viral": {
    "Viral Ideas": 30,
    "Viral Stories": 40,
    "Viral Experiences": 50,
    "Viral Highlights": 30,
    "Viral Discoveries": 40,
    "Viral Recommendations": 20,
    "Viral Guides": 40,
    "Viral Collections": 30,
    "Viral Moments": 30,
    "Viral Events": 40,
    "Viral Trends": 30,
    "Viral Communities": 40,
    "Viral Projects": 70,
    "Viral Challenges": 100,
    "Viral Favorites": 20,
    "Viral Tips": 30,
    "Viral Reviews": 20,
    "Viral Inspiration": 30,
    "Viral News": 20,
    "Viral Showcase": 60
  },
  "Reactions": {
    "Reactions Ideas": 20,
    "Reactions Stories": 30,
    "Reactions Experiences": 30,
    "Reactions Highlights": 20,
    "Reactions Discoveries": 30,
    "Reactions Recommendations": 20,
    "Reactions Guides": 30,
    "Reactions Collections": 20,
    "Reactions Moments": 20,
    "Reactions Events": 30,
    "Reactions Trends": 20,
    "Reactions Communities": 30,
    "Reactions Projects": 40,
    "Reactions Challenges": 60,
    "Reactions Favorites": 10,
    "Reactions Tips": 20,
    "Reactions Reviews": 20,
    "Reactions Inspiration": 20,
    "Reactions News": 10,
    "Reactions Showcase": 40
  },
  "Polls": {
    "Polls Ideas": 20,
    "Polls Stories": 30,
    "Polls Experiences": 30,
    "Polls Highlights": 20,
    "Polls Discoveries": 30,
    "Polls Recommendations": 20,
    "Polls Guides": 30,
    "Polls Collections": 20,
    "Polls Moments": 20,
    "Polls Events": 30,
    "Polls Trends": 20,
    "Polls Communities": 30,
    "Polls Projects": 40,
    "Polls Challenges": 60,
    "Polls Favorites": 10,
    "Polls Tips": 20,
    "Polls Reviews": 20,
    "Polls Inspiration": 20,
    "Polls News": 10,
    "Polls Showcase": 40
  },
  "Discussions": {
    "Discussions Ideas": 30,
    "Discussions Stories": 40,
    "Discussions Experiences": 50,
    "Discussions Highlights": 30,
    "Discussions Discoveries": 50,
    "Discussions Recommendations": 30,
    "Discussions Guides": 60,
    "Discussions Collections": 40,
    "Discussions Moments": 30,
    "Discussions Events": 40,
    "Discussions Trends": 30,
    "Discussions Communities": 50,
    "Discussions Projects": 80,
    "Discussions Challenges": 100,
    "Discussions Favorites": 20,
    "Discussions Tips": 40,
    "Discussions Reviews": 30,
    "Discussions Inspiration": 40,
    "Discussions News": 20,
    "Discussions Showcase": 60
  },
  "Stories": {
    "Stories Ideas": 30,
    "Stories Stories": 40,
    "Stories Experiences": 60,
    "Stories Highlights": 40,
    "Stories Discoveries": 50,
    "Stories Recommendations": 30,
    "Stories Guides": 50,
    "Stories Collections": 40,
    "Stories Moments": 50,
    "Stories Events": 40,
    "Stories Trends": 30,
    "Stories Communities": 50,
    "Stories Projects": 80,
    "Stories Challenges": 100,
    "Stories Favorites": 20,
    "Stories Tips": 40,
    "Stories Reviews": 30,
    "Stories Inspiration": 60,
    "Stories News": 20,
    "Stories Showcase": 70
  },
  "Memories": {
    "Memories Ideas": 30,
    "Memories Stories": 50,
    "Memories Experiences": 70,
    "Memories Highlights": 40,
    "Memories Discoveries": 40,
    "Memories Recommendations": 20,
    "Memories Guides": 40,
    "Memories Collections": 50,
    "Memories Moments": 50,
    "Memories Events": 40,
    "Memories Trends": 20,
    "Memories Communities": 40,
    "Memories Projects": 70,
    "Memories Challenges": 80,
    "Memories Favorites": 20,
    "Memories Tips": 30,
    "Memories Reviews": 20,
    "Memories Inspiration": 50,
    "Memories News": 10,
    "Memories Showcase": 60
  },
  "Friendships": {
    "Friendships Ideas": 30,
    "Friendships Stories": 60,
    "Friendships Experiences": 80,
    "Friendships Highlights": 40,
    "Friendships Discoveries": 50,
    "Friendships Recommendations": 30,
    "Friendships Guides": 60,
    "Friendships Collections": 40,
    "Friendships Moments": 60,
    "Friendships Events": 40,
    "Friendships Trends": 20,
    "Friendships Communities": 50,
    "Friendships Projects": 80,
    "Friendships Challenges": 120,
    "Friendships Favorites": 20,
    "Friendships Tips": 60,
    "Friendships Reviews": 30,
    "Friendships Inspiration": 60,
    "Friendships News": 20,
    "Friendships Showcase": 70
  }
};

// Normalized lowercase lookup map for robust case-insensitive matching
const NORMALIZED_LOOKUP = {};
for (const [catName, subMap] of Object.entries(CATEGORY_XP_MAP)) {
  const normCat = catName.trim().toLowerCase();
  NORMALIZED_LOOKUP[normCat] = {
    canonicalName: catName,
    subcategories: {}
  };
  for (const [subName, xp] of Object.entries(subMap)) {
    const normSub = subName.trim().toLowerCase();
    NORMALIZED_LOOKUP[normCat].subcategories[normSub] = {
      canonicalName: subName,
      xp: xp
    };
  }
}

/**
 * Resolves the fixed XP for a given category and subcategory.
 * Returns null if the category or subcategory is invalid.
 * 
 * @param {string} category 
 * @param {string} subcategory 
 * @returns {{ valid: boolean, category: string, subcategory: string, xp: number } | null}
 */
function getXpForActivity(category, subcategory) {
  if (!category || !subcategory || typeof category !== 'string' || typeof subcategory !== 'string') {
    return null;
  }

  const normCat = category.trim().toLowerCase();
  const normSub = subcategory.trim().toLowerCase();

  const catEntry = NORMALIZED_LOOKUP[normCat];
  if (!catEntry) {
    return null;
  }

  const subEntry = catEntry.subcategories[normSub];
  if (!subEntry) {
    return null;
  }

  return {
    valid: true,
    category: catEntry.canonicalName,
    subcategory: subEntry.canonicalName,
    xp: subEntry.xp
  };
}

/**
 * Validates the entire mapping against the authoritative specification.
 * 
 * Expected:
 * - Categories: 100
 * - Activities: 2000
 * - Total XP: 152220
 * - Minimum XP: 10
 * - Maximum XP: 500
 * - Average XP: 76.11
 * 
 * @returns {Object}
 */
function validateXpMapping() {
  const categories = Object.keys(CATEGORY_XP_MAP);
  let activitiesCount = 0;
  let totalXp = 0;
  let minXp = Infinity;
  let maxXp = -Infinity;
  const categoryDetails = [];

  for (const cat of categories) {
    const subcats = Object.keys(CATEGORY_XP_MAP[cat]);
    activitiesCount += subcats.length;
    let catXp = 0;
    for (const sub of subcats) {
      const xp = CATEGORY_XP_MAP[cat][sub];
      totalXp += xp;
      catXp += xp;
      if (xp < minXp) minXp = xp;
      if (xp > maxXp) maxXp = xp;
    }
    categoryDetails.push({ category: cat, subcategoriesCount: subcats.length, totalXp: catXp });
  }

  const averageXp = activitiesCount > 0 ? parseFloat((totalXp / activitiesCount).toFixed(2)) : 0;

  const isValid = (
    categories.length === 100 &&
    activitiesCount === 2000 &&
    totalXp === 152220 &&
    minXp === 10 &&
    maxXp === 500 &&
    averageXp === 76.11
  );

  return {
    categoriesCount: categories.length,
    activitiesCount,
    totalXp,
    minXp,
    maxXp,
    averageXp,
    isValid,
    expected: {
      categoriesCount: 100,
      activitiesCount: 2000,
      totalXp: 152220,
      minXp: 10,
      maxXp: 500,
      averageXp: 76.11
    }
  };
}

/**
 * Returns all categories and their subcategories with XP.
 */
function getAllCategoriesWithXp() {
  return CATEGORY_XP_MAP;
}

module.exports = {
  CATEGORY_XP_MAP,
  getXpForActivity,
  validateXpMapping,
  getAllCategoriesWithXp
};
